export default {
  ARROW_UP: '/images/icons/arrowUp-icon.svg',
  ARROW_LEFT: '/images/icons/arrow-left.svg',
  ARROW_DOWN: '/images/icons/arrow-down-icon.svg',
  CALENDAR: '/images/icons/calendar-icon.svg',
  CARCONNECT_BRAND: '/images/brands/brand-white.png',
  CARCONNECT_LOGO: '/images/brands/brand.png',
  CLEAR_DATA: '/images/icons/clearData-icon.svg',
  CLOSE: '/images/icons/close-icon.svg',
  CHECK: '/images/icons/check-icon.svg',
  DASHBOARD: '/images/icons/leadsCapture-icon.svg',
  DELETE: '/images/icons/delete-icon.svg',
  FILTER: '/images/icons/filter-icon.svg',
  MENU: '/images/icons/menu-icon.svg',
  WARNING: '/images/icons/warning-icon.svg',
  SEARCH: '/images/icons/search-icon.svg',
  PENCIL: '/images/icons/pencil-icon.svg',
  ADD: '/images/icons/add-icon.svg',
  ARROW_RIGHT: '/images/icons/arrow-right.svg',
  LOGOUT: '/images/icons/logout.svg',
  ANALYTICS_DASHBOARD:
    '/images/icons/bi-vehicle-intelligence/analyticsDashboard.svg',
  SUMMARY: '/images/icons/bi-vehicle-intelligence/summary.svg',
  CALENDAR_VW: '/images/icons/bi-vehicle-intelligence/calendar-vw.svg',
  FILTER_VW: '/images/icons/bi-vehicle-intelligence/filter-vw.svg',
  INTERACTION: '/images/icons/bi-vehicle-intelligence/interaction.svg',
  LEAD_MANAGEMENT_AND_ALERTS:
    '/images/icons/bi-vehicle-intelligence/leadManagementAndAlerts.svg',
  DOTS: '/images/icons/dots.svg',
  INFO_TOOLTIP: '/images/icons/info-icon.svg',
}
