name: Continuous deployment for Gendocs frontend

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build artifacts
        env:
          ENV_FILE_CREDENTIALS: ${{ secrets.ENV_FILE_CREDENTIALS }}
        run: |
          echo "$ENV_FILE_CREDENTIALS" > ./.env

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production
          push: true
          tags: leninner/gendocsv3-frontend:latest
